// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Provides live risk scores for each supplier, combining financial health, delivery history, news sentiment, and geopolitical indicators.
 *
 * - getSupplierVitalityScore - A function that retrieves the supplier vitality score.
 */

import {ai} from '@/ai/genkit';
// Import schemas and types from the new types file
import {
  SupplierVitalityScoreInputSchema,
  type SupplierVitalityScoreInput,
  SupplierVitalityScoreOutputSchema,
  type SupplierVitalityScoreOutput,
} from './types/supplier-vitality-types'; 

export async function getSupplierVitalityScore(input: SupplierVitalityScoreInput): Promise<SupplierVitalityScoreOutput> {
  return supplierVitalityScoreFlow(input);
}

const prompt = ai.definePrompt({
  name: 'supplierVitalityScorePrompt',
  input: {schema: SupplierVitalityScoreInputSchema}, 
  output: {schema: SupplierVitalityScoreOutputSchema}, 
  prompt: `You are a supply chain risk analyst. Analyze the provided data to generate a vitality score, risk assessment, and recommendations for the supplier.

Supplier Name: {{{supplierName}}}
Financial Health: {{{financialHealth}}}
Delivery History: {{{deliveryHistory}}}
News Sentiment: {{{newsSentiment}}}
Geopolitical Indicators: {{{geopoliticalIndicators}}}

Generate a vitality score (0-100, higher is better), a risk assessment, and recommendations to mitigate potential supplier-related risks.
`,
});

const supplierVitalityScoreFlow = ai.defineFlow(
  {
    name: 'supplierVitalityScoreFlow',
    inputSchema: SupplierVitalityScoreInputSchema, 
    outputSchema: SupplierVitalityScoreOutputSchema, 
  },
  async (input: SupplierVitalityScoreInput) => { 
    const {output} = await prompt(input);
    return output!;
  }
);
